sudo: false
language: cpp

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++4.8

before_install:
    - chmod u+x ./ghscript.sh

script:
    - echo "none"

after_success:
    - ./ghscript.sh
