sudo: false
language: cpp

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.9-multilib

before_install:
    - chmod u+x ./ghscript.sh

script:
    - g++ -v

after_success:
    - ./ghscript.sh
