sudo: false
language: cpp

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9

before_install:
    - chmod u+x ./ghscript.sh
    
script:
    - g++ -v
    - ls -la 
    - echo $HOME
    - ls -la $HOME

after_success:
    - ./ghscript.sh
