sudo: required
language: cpp
before_install:
    - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa -y && sudo apt-get update -q && sudo apt-get install qtchooser qt5-qmake libboost-all-dev -y
    - export QT_SELECT=qt5
script:
    - echo "none"
