sudo: false
language: cpp

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9

before_install:
    - chmod u+x ./ghscript.sh
    - find /usr/bin -type f -name "g++*"
    
script:
    - g++ -v

after_success:
    - ./ghscript.sh
