sudo: required
language: cpp
before_install:
    - sudo apt-get update && sudo apt-get install -y qt4-qmake libboost-test-dev
script:
    - MAKESPECS=(g++ clang); for MK in "${MAKESPECS[@]}"; do mkdir qmake-linux-$MK && cd qmake-linux-$MK && qmake -spec linux-$MK .. && make && ./travistests; done
